version: "3.1"
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    volumes:
      - ./templates:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
